=== arnaudpourbaix/bgee-mods-installer/assets/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/Config",
    "definitions": {
        "Config": {
            "type": "object",
            "properties": {
                "gameFolder": {
                    "type": "string"
                },
                "modsFolders": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "weiduLocation": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "mods": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Mod"
                    }
                },
                "externalMods": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ExternalMod"
                    }
                }
            },
            "required": [
                "gameFolder",
                "modsFolders",
                "weiduLocation",
                "language",
                "mods",
                "externalMods"
            ],
            "additionalProperties": false
        },
        "Mod": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "tp2File": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                },
                "language": {
                    "$ref": "#/definitions/ValueName"
                },
                "components": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ModComponent"
                    }
                }
            },
            "required": [
                "components",
                "language",
                "name",
                "tp2File",
                "version"
            ],
            "additionalProperties": false
        },
        "ValueName": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                }
            },
            "required": [
                "value",
                "name"
            ],
            "additionalProperties": false
        },
        "ModComponent": {
            "type": "object",
            "properties": {
                "num": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "install": {
                    "type": "boolean"
                }
            },
            "required": [
                "num",
                "name",
                "install"
            ],
            "additionalProperties": false
        },
        "ExternalMod": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "tp2File": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                },
                "copy": {
                    "type": "boolean"
                }
            },
            "required": [
                "copy",
                "name",
                "tp2File",
                "version"
            ],
            "additionalProperties": false
        }
    }
}

=== arnaudpourbaix/bgee-mods-installer/assets/config.json
{
  "gameFolder": "C:/Games/Baldur's Gate Enhanced Edition",
  "modsFolders": [
    "Z:/games/bg/mods/bg1",
    "Z:/games/bg/mods/both"
  ],
  "language": "English",
  "weiduLocation": "C:/Games/Baldur's Gate Enhanced Edition/weidu.exe",
  "mods": [
    {
      "name": "bg1re",
      "tp2File": "bg1re/setup-bg1re.tp2",
      "version": "13",
      "language": {
        "value": 0,
        "name": "English"
      },
      "components": [
        {
          "num": 1,
          "name": "Bardolan's Briefing, by berelinde",
          "install": false
        },
        {
          "num": 2,
          "name": "Scar's Spare Time, by jastey",
          "install": false
        },
        {
          "num": 3,
          "name": "Kim's Preoccupation, by jastey (WARNING - refer to the readme!)",
          "install": false
        },
        {
          "num": 4,
          "name": "Extension of Bjornin Encounter (Personal Wound Treatment), by jastey",
          "install": false
        },
        {
          "num": 5,
          "name": "No Starch in the Maypole",
          "install": false
        },
        {
          "num": 6,
          "name": "Duke Eltan's Spare Minute, by jastey",
          "install": false
        },
        {
          "num": 7,
          "name": "Husam's Personal Preparation, by jastey",
          "install": false
        },
        {
          "num": 8,
          "name": "Laurel's Post-Hunting, by jastey",
          "install": false
        },
        {
          "num": 9,
          "name": "Bartus' Seduction, by jastey",
          "install": false
        },
        {
          "num": 10,
          "name": "Lina's Massage, by jastey",
          "install": false
        },
        {
          "num": 11,
          "name": "First Night with Quentin, by Kulyok",
          "install": false
        },
        {
          "num": 12,
          "name": "Chatting Niklos Up, by Kulyok (mature content. WARNING - refer to the readme!)",
          "install": false
        },
        {
          "num": 13,
          "name": "Slythe and Krystin, by Kulyok (mature content. WARNING - refer to the readme!)",
          "install": false
        },
        {
          "num": 14,
          "name": "No Regrets",
          "install": false
        },
        {
          "num": 15,
          "name": "Purchased Love, by Thimblerig",
          "install": false
        },
        {
          "num": 16,
          "name": "Hull: Heavy Duty, by Lava",
          "install": false
        },
        {
          "num": 17,
          "name": "Late Night with Jaheira, by Kulyok",
          "install": false
        },
        {
          "num": 18,
          "name": "Sil's Blessing, by Lava",
          "install": false
        },
        {
          "num": 19,
          "name": "Melicamp: The Poultry Boy, by Lava",
          "install": false
        },
        {
          "num": 20,
          "name": "Reading with Rinnie, by Western Paladin",
          "install": false
        },
        {
          "num": 21,
          "name": "Molly the Husband-Grabber, by Kulyok",
          "install": false
        },
        {
          "num": 22,
          "name": "The Mourning of Centeol, the Spider Lady, by Lava",
          "install": false
        },
        {
          "num": 23,
          "name": "The Essential End, by Lava (WARNING - refer to the readme!)",
          "install": false
        },
        {
          "num": 24,
          "name": "The Harvestmen Lair, by Lava (mature content)",
          "install": false
        },
        {
          "num": 25,
          "name": "The Great Zudini, by Kulyok (mature content)",
          "install": false
        },
        {
          "num": 26,
          "name": "The Messenger, by Thimblerig",
          "install": false
        },
        {
          "num": 27,
          "name": "Ender Sai, the Hero's Reward, by Thimblerig (WARNING - refer to the readme!)",
          "install": false
        },
        {
          "num": 28,
          "name": "The Novelists, by Thimblerig",
          "install": false
        },
        {
          "num": 29,
          "name": "The Honest Lies of Two Riversides, By Lava",
          "install": false
        },
        {
          "num": 30,
          "name": "Necromancer's Trouble, by jastey",
          "install": false
        },
        {
          "num": 31,
          "name": "Dinner with Thalantyr, by jastey",
          "install": false
        },
        {
          "num": 32,
          "name": "Girdle of Gender Reactions, by Thimblerig, Kulyok, Domi, Lava, Lastknightleft, Twani, Jastey, Daisy Ninja Girl",
          "install": false
        },
        {
          "num": 33,
          "name": "The Surgeon's Dream, by Kulyok",
          "install": false
        },
        {
          "num": 34,
          "name": "All That Left Was, by Lava and Thimblerig",
          "install": false
        },
        {
          "num": 35,
          "name": "A Childhood Friend, by Kulyok",
          "install": false
        },
        {
          "num": 36,
          "name": "Arlene the Working Girl, by Kulyok",
          "install": false
        },
        {
          "num": 37,
          "name": "Della May from Thay, by Kulyok",
          "install": false
        },
        {
          "num": 38,
          "name": "A Dirty Guard in Candlekeep, by Kulyok (mature content. WARNING - refer to the readme!)",
          "install": false
        },
        {
          "num": 39,
          "name": "Phoenix Flame, by Kulyok (mature content)",
          "install": false
        },
        {
          "num": 40,
          "name": "Mikala the Monk, by Twani",
          "install": false
        },
        {
          "num": 41,
          "name": "The Messenger 2: Rain or Snow or Gloom of Night, by Thimblerig and tibicina",
          "install": false
        },
        {
          "num": 42,
          "name": "Camryn and Tamah, by tibicina",
          "install": false
        },
        {
          "num": 43,
          "name": "Minor Disclosures, by jastey",
          "install": false
        },
        {
          "num": 44,
          "name": "Cloakwood Lovers, by tibicina",
          "install": false
        },
        {
          "num": 100,
          "name": "Main Component: Amount of -ahem- details and BG-style vs. description text! (Required) -> Teen Version and Skip Components with Warnings.",
          "install": false
        },
        {
          "num": 101,
          "name": "Main Component: Amount of -ahem- details and BG-style vs. description text! (Required) -> Teen Version and Show/Install all Components with Warnings.",
          "install": false
        },
        {
          "num": 102,
          "name": "Main Component: Amount of -ahem- details and BG-style vs. description text! (Required) -> BG-style Version [Adult content] and Skip Components with Warnings.",
          "install": false
        },
        {
          "num": 103,
          "name": "Main Component: Amount of -ahem- details and BG-style vs. description text! (Required) -> BG-style Version [Adult content] and Show/Install all Components with Warnings.",
          "install": false
        },
        {
          "num": 104,
          "name": "Main Component: Amount of -ahem- details and BG-style vs. description text! (Required) -> Descriptive Version [Adult content] and Skip Components with Warnings.",
          "install": false
        },
        {
          "num": 105,
          "name": "Main Component: Amount of -ahem- details and BG-style vs. description text! (Required) -> Descriptive Version [Adult content] and Show/Install all Components with Warnings.",
          "install": false
        }
      ]
    }
  ],
  "externalMods": [
    {
      "name": "gorgon",
      "tp2File": "Z:/games/bg/mods/bg1/gorgon-v4.8/gorgon/setup-gorgon.tp2",
      "version": "v4.8",
      "copy": true
    },
    {
      "name": "bg1npc",
      "tp2File": "Z:/games/bg/mods/bg1/the-bg1npc-project-v32/bg1npc/bg1npc.tp2",
      "version": "v32",
      "copy": true
    },
    {
      "name": "bg1npcmusic",
      "tp2File": "Z:/games/bg/mods/bg1/bg1npcmusic/setup-bg1npcmusic.tp2",
      "version": "v6",
      "copy": true
    },
    {
      "name": "bst",
      "tp2File": "Z:/games/bg/mods/bg1/bs-baldurans-seatower-veaob.9/bst/setup-bst.tp2",
      "version": "vEAOB.9",
      "copy": true
    },
    {
      "name": "Vienxay",
      "tp2File": "Z:/games/bg/mods/bg1/Vienxay-BG1-master/Vienxay/Vienxay.tp2",
      "version": "1.67",
      "copy": true
    },
    {
      "name": "Recorder",
      "tp2File": "Z:/games/bg/mods/bg1/Recorder-BG1-master/Recorder/Setup-Recorder.tp2",
      "version": "1.51",
      "copy": true
    },
    {
      "name": "DlcMerger",
      "tp2File": "Z:/games/bg/mods/bg1/win-64bit-DlcMerger-v1.7/DlcMerger/DlcMerger.tp2",
      "version": "1.7",
      "copy": true
    },
    {
      "name": "glamnpcpack",
      "tp2File": "Z:/games/bg/mods/bg1/glamnpcpack-v5/glamnpcpack/setup-glamnpcpack.tp2",
      "version": "v5",
      "copy": true
    },
    {
      "name": "Helga",
      "tp2File": "Z:/games/bg/mods/bg1/Helga-BG1-master/Helga/setup-Helga.TP2",
      "version": "1.56",
      "copy": true
    },
    {
      "name": "bgqe",
      "tp2File": "Z:/games/bg/mods/bg1/baldurs-gate-mini-quests-and-encounters-modification-29/bgqe/setup-bgqe.tp2",
      "version": "29",
      "copy": true
    },
    {
      "name": "thecalling",
      "tp2File": "Z:/games/bg/mods/bg1/thecalling-v5/thecalling/thecalling.tp2",
      "version": "v5",
      "copy": true
    },
    {
      "name": "IndiNPC",
      "tp2File": "Z:/games/bg/mods/bg1/indira-npc-v15.1/IndiNPC/IndiNPC.tp2",
      "version": "v15.1",
      "copy": true
    },
    {
      "name": "BGEEClassicMovies",
      "tp2File": "Z:/games/bg/mods/bg1/bgee-classic-movies-v2.3.1/BGEEClassicMovies/BGEEClassicMovies.tp2",
      "version": "v2.3.1",
      "copy": true
